[project]
name = "a2a-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk>=0.2.9",
    "dotenv>=0.9.9",
    "langchain-anthropic>=0.3.15",
    "langgraph>=0.4.8",
    "python-a2a>=0.5.9",
]
